batch_size: 512
epochs: 100
eval_every_n_epochs: 25
fine_tune_from: ''
log_every_n_steps: 100
weight_decay: 10e-6
fp16_precision: True
n_gpu: 8
gpu_ids: (0,1,2,3,4,5,6,7)

model:
  out_dim: 256
  base_model: "resnet18"

dataset:
  s: 1
  input_shape: (256,256,3)
  num_workers: 8
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True
